#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FinalICBF")]
	public partial class ORMicbfDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertPersona(Persona instance);
    partial void UpdatePersona(Persona instance);
    partial void DeletePersona(Persona instance);
    partial void InsertRegistro_Avance_Academico(Registro_Avance_Academico instance);
    partial void UpdateRegistro_Avance_Academico(Registro_Avance_Academico instance);
    partial void DeleteRegistro_Avance_Academico(Registro_Avance_Academico instance);
    partial void InsertRegistro_Jardin(Registro_Jardin instance);
    partial void UpdateRegistro_Jardin(Registro_Jardin instance);
    partial void DeleteRegistro_Jardin(Registro_Jardin instance);
    partial void InsertRegistroNinios(RegistroNinios instance);
    partial void UpdateRegistroNinios(RegistroNinios instance);
    partial void DeleteRegistroNinios(RegistroNinios instance);
    partial void InsertRol(Rol instance);
    partial void UpdateRol(Rol instance);
    partial void DeleteRol(Rol instance);
    partial void InsertAnuncios(Anuncios instance);
    partial void UpdateAnuncios(Anuncios instance);
    partial void DeleteAnuncios(Anuncios instance);
    partial void InsertRegistro_Asistencia(Registro_Asistencia instance);
    partial void UpdateRegistro_Asistencia(Registro_Asistencia instance);
    partial void DeleteRegistro_Asistencia(Registro_Asistencia instance);
    #endregion
		
		public ORMicbfDataDataContext() : 
				base(global::Datos.Properties.Settings.Default.FinalICBFConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ORMicbfDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMicbfDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMicbfDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMicbfDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Persona> Persona
		{
			get
			{
				return this.GetTable<Persona>();
			}
		}
		
		public System.Data.Linq.Table<Registro_Avance_Academico> Registro_Avance_Academico
		{
			get
			{
				return this.GetTable<Registro_Avance_Academico>();
			}
		}
		
		public System.Data.Linq.Table<Registro_Jardin> Registro_Jardin
		{
			get
			{
				return this.GetTable<Registro_Jardin>();
			}
		}
		
		public System.Data.Linq.Table<RegistroNinios> RegistroNinios
		{
			get
			{
				return this.GetTable<RegistroNinios>();
			}
		}
		
		public System.Data.Linq.Table<Rol> Rol
		{
			get
			{
				return this.GetTable<Rol>();
			}
		}
		
		public System.Data.Linq.Table<Anuncios> Anuncios
		{
			get
			{
				return this.GetTable<Anuncios>();
			}
		}
		
		public System.Data.Linq.Table<Registro_Asistencia> Registro_Asistencia
		{
			get
			{
				return this.GetTable<Registro_Asistencia>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LOGIN")]
		public ISingleResult<SP_LOGINResult> SP_LOGIN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Clave", DbType="VarChar(10)")] string clave)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correo, clave);
			return ((ISingleResult<SP_LOGINResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LOGIN_WEB")]
		public ISingleResult<SP_LOGIN_WEBResult> SP_LOGIN_WEB([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Clave", DbType="VarChar(10)")] string clave)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correo, clave);
			return ((ISingleResult<SP_LOGIN_WEBResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Persona")]
	public partial class Persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Cedula;
		
		private string _Nombres;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Telefono;
		
		private string _Celular;
		
		private string _Direccion;
		
		private string _Correo;
		
		private string _Clave;
		
		private int _idRol;
		
		private EntitySet<Registro_Jardin> _Registro_Jardin;
		
		private EntitySet<RegistroNinios> _RegistroNinios;
		
		private EntityRef<Rol> _Rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCedulaChanging(long value);
    partial void OnCedulaChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnFechaNacimientoChanging(System.DateTime value);
    partial void OnFechaNacimientoChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnClaveChanging(string value);
    partial void OnClaveChanged();
    partial void OnidRolChanging(int value);
    partial void OnidRolChanged();
    #endregion
		
		public Persona()
		{
			this._Registro_Jardin = new EntitySet<Registro_Jardin>(new Action<Registro_Jardin>(this.attach_Registro_Jardin), new Action<Registro_Jardin>(this.detach_Registro_Jardin));
			this._RegistroNinios = new EntitySet<RegistroNinios>(new Action<RegistroNinios>(this.attach_RegistroNinios), new Action<RegistroNinios>(this.detach_RegistroNinios));
			this._Rol = default(EntityRef<Rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this.OnClaveChanging(value);
					this.SendPropertyChanging();
					this._Clave = value;
					this.SendPropertyChanged("Clave");
					this.OnClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRol", DbType="Int NOT NULL")]
		public int idRol
		{
			get
			{
				return this._idRol;
			}
			set
			{
				if ((this._idRol != value))
				{
					if (this._Rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRolChanging(value);
					this.SendPropertyChanging();
					this._idRol = value;
					this.SendPropertyChanged("idRol");
					this.OnidRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Registro_Jardin", Storage="_Registro_Jardin", ThisKey="Cedula", OtherKey="IdMadreComunitaria")]
		public EntitySet<Registro_Jardin> Registro_Jardin
		{
			get
			{
				return this._Registro_Jardin;
			}
			set
			{
				this._Registro_Jardin.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_RegistroNinios", Storage="_RegistroNinios", ThisKey="Cedula", OtherKey="DocAcudiente")]
		public EntitySet<RegistroNinios> RegistroNinios
		{
			get
			{
				return this._RegistroNinios;
			}
			set
			{
				this._RegistroNinios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Persona", Storage="_Rol", ThisKey="idRol", OtherKey="idRol", IsForeignKey=true)]
		public Rol Rol
		{
			get
			{
				return this._Rol.Entity;
			}
			set
			{
				Rol previousValue = this._Rol.Entity;
				if (((previousValue != value) 
							|| (this._Rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rol.Entity = null;
						previousValue.Persona.Remove(this);
					}
					this._Rol.Entity = value;
					if ((value != null))
					{
						value.Persona.Add(this);
						this._idRol = value.idRol;
					}
					else
					{
						this._idRol = default(int);
					}
					this.SendPropertyChanged("Rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Registro_Jardin(Registro_Jardin entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Registro_Jardin(Registro_Jardin entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_RegistroNinios(RegistroNinios entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_RegistroNinios(RegistroNinios entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Registro_Avance_Academico")]
	public partial class Registro_Avance_Academico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _CodRegistro;
		
		private long _idNinio;
		
		private int _AnioEscolar;
		
		private string _Nivel;
		
		private string _Notas;
		
		private string _Descripcion;
		
		private System.DateTime _FechaEntregaNota;
		
		private EntityRef<RegistroNinios> _RegistroNinios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodRegistroChanging(long value);
    partial void OnCodRegistroChanged();
    partial void OnidNinioChanging(long value);
    partial void OnidNinioChanged();
    partial void OnAnioEscolarChanging(int value);
    partial void OnAnioEscolarChanged();
    partial void OnNivelChanging(string value);
    partial void OnNivelChanged();
    partial void OnNotasChanging(string value);
    partial void OnNotasChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnFechaEntregaNotaChanging(System.DateTime value);
    partial void OnFechaEntregaNotaChanged();
    #endregion
		
		public Registro_Avance_Academico()
		{
			this._RegistroNinios = default(EntityRef<RegistroNinios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodRegistro", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long CodRegistro
		{
			get
			{
				return this._CodRegistro;
			}
			set
			{
				if ((this._CodRegistro != value))
				{
					this.OnCodRegistroChanging(value);
					this.SendPropertyChanging();
					this._CodRegistro = value;
					this.SendPropertyChanged("CodRegistro");
					this.OnCodRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNinio", DbType="BigInt NOT NULL")]
		public long idNinio
		{
			get
			{
				return this._idNinio;
			}
			set
			{
				if ((this._idNinio != value))
				{
					if (this._RegistroNinios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidNinioChanging(value);
					this.SendPropertyChanging();
					this._idNinio = value;
					this.SendPropertyChanged("idNinio");
					this.OnidNinioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnioEscolar", DbType="Int NOT NULL")]
		public int AnioEscolar
		{
			get
			{
				return this._AnioEscolar;
			}
			set
			{
				if ((this._AnioEscolar != value))
				{
					this.OnAnioEscolarChanging(value);
					this.SendPropertyChanging();
					this._AnioEscolar = value;
					this.SendPropertyChanged("AnioEscolar");
					this.OnAnioEscolarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nivel
		{
			get
			{
				return this._Nivel;
			}
			set
			{
				if ((this._Nivel != value))
				{
					this.OnNivelChanging(value);
					this.SendPropertyChanging();
					this._Nivel = value;
					this.SendPropertyChanged("Nivel");
					this.OnNivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notas", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Notas
		{
			get
			{
				return this._Notas;
			}
			set
			{
				if ((this._Notas != value))
				{
					this.OnNotasChanging(value);
					this.SendPropertyChanging();
					this._Notas = value;
					this.SendPropertyChanged("Notas");
					this.OnNotasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEntregaNota", DbType="DateTime NOT NULL")]
		public System.DateTime FechaEntregaNota
		{
			get
			{
				return this._FechaEntregaNota;
			}
			set
			{
				if ((this._FechaEntregaNota != value))
				{
					this.OnFechaEntregaNotaChanging(value);
					this.SendPropertyChanging();
					this._FechaEntregaNota = value;
					this.SendPropertyChanged("FechaEntregaNota");
					this.OnFechaEntregaNotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RegistroNinios_Registro_Avance_Academico", Storage="_RegistroNinios", ThisKey="idNinio", OtherKey="RegistroNIUP", IsForeignKey=true)]
		public RegistroNinios RegistroNinios
		{
			get
			{
				return this._RegistroNinios.Entity;
			}
			set
			{
				RegistroNinios previousValue = this._RegistroNinios.Entity;
				if (((previousValue != value) 
							|| (this._RegistroNinios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RegistroNinios.Entity = null;
						previousValue.Registro_Avance_Academico.Remove(this);
					}
					this._RegistroNinios.Entity = value;
					if ((value != null))
					{
						value.Registro_Avance_Academico.Add(this);
						this._idNinio = value.RegistroNIUP;
					}
					else
					{
						this._idNinio = default(long);
					}
					this.SendPropertyChanged("RegistroNinios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Registro_Jardin")]
	public partial class Registro_Jardin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdJardin;
		
		private string _NombreJardin;
		
		private string _DireccionJardin;
		
		private string _EstadoJardin;
		
		private long _IdMadreComunitaria;
		
		private EntitySet<RegistroNinios> _RegistroNinios;
		
		private EntityRef<Persona> _Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdJardinChanging(int value);
    partial void OnIdJardinChanged();
    partial void OnNombreJardinChanging(string value);
    partial void OnNombreJardinChanged();
    partial void OnDireccionJardinChanging(string value);
    partial void OnDireccionJardinChanged();
    partial void OnEstadoJardinChanging(string value);
    partial void OnEstadoJardinChanged();
    partial void OnIdMadreComunitariaChanging(long value);
    partial void OnIdMadreComunitariaChanged();
    #endregion
		
		public Registro_Jardin()
		{
			this._RegistroNinios = new EntitySet<RegistroNinios>(new Action<RegistroNinios>(this.attach_RegistroNinios), new Action<RegistroNinios>(this.detach_RegistroNinios));
			this._Persona = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdJardin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdJardin
		{
			get
			{
				return this._IdJardin;
			}
			set
			{
				if ((this._IdJardin != value))
				{
					this.OnIdJardinChanging(value);
					this.SendPropertyChanging();
					this._IdJardin = value;
					this.SendPropertyChanged("IdJardin");
					this.OnIdJardinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreJardin", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreJardin
		{
			get
			{
				return this._NombreJardin;
			}
			set
			{
				if ((this._NombreJardin != value))
				{
					this.OnNombreJardinChanging(value);
					this.SendPropertyChanging();
					this._NombreJardin = value;
					this.SendPropertyChanged("NombreJardin");
					this.OnNombreJardinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireccionJardin", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DireccionJardin
		{
			get
			{
				return this._DireccionJardin;
			}
			set
			{
				if ((this._DireccionJardin != value))
				{
					this.OnDireccionJardinChanging(value);
					this.SendPropertyChanging();
					this._DireccionJardin = value;
					this.SendPropertyChanged("DireccionJardin");
					this.OnDireccionJardinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoJardin", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string EstadoJardin
		{
			get
			{
				return this._EstadoJardin;
			}
			set
			{
				if ((this._EstadoJardin != value))
				{
					this.OnEstadoJardinChanging(value);
					this.SendPropertyChanging();
					this._EstadoJardin = value;
					this.SendPropertyChanged("EstadoJardin");
					this.OnEstadoJardinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMadreComunitaria", DbType="BigInt NOT NULL")]
		public long IdMadreComunitaria
		{
			get
			{
				return this._IdMadreComunitaria;
			}
			set
			{
				if ((this._IdMadreComunitaria != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMadreComunitariaChanging(value);
					this.SendPropertyChanging();
					this._IdMadreComunitaria = value;
					this.SendPropertyChanged("IdMadreComunitaria");
					this.OnIdMadreComunitariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Registro_Jardin_RegistroNinios", Storage="_RegistroNinios", ThisKey="IdJardin", OtherKey="IdJardin")]
		public EntitySet<RegistroNinios> RegistroNinios
		{
			get
			{
				return this._RegistroNinios;
			}
			set
			{
				this._RegistroNinios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Registro_Jardin", Storage="_Persona", ThisKey="IdMadreComunitaria", OtherKey="Cedula", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Registro_Jardin.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Registro_Jardin.Add(this);
						this._IdMadreComunitaria = value.Cedula;
					}
					else
					{
						this._IdMadreComunitaria = default(long);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RegistroNinios(RegistroNinios entity)
		{
			this.SendPropertyChanging();
			entity.Registro_Jardin = this;
		}
		
		private void detach_RegistroNinios(RegistroNinios entity)
		{
			this.SendPropertyChanging();
			entity.Registro_Jardin = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RegistroNinios")]
	public partial class RegistroNinios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _RegistroNIUP;
		
		private string _Nombre;
		
		private System.DateTime _FechaNac;
		
		private string _TipoSangre;
		
		private string _CiudadNacimiento;
		
		private long _DocAcudiente;
		
		private string _Telefono;
		
		private string _Direccion;
		
		private string _EPS;
		
		private System.Nullable<int> _IdJardin;
		
		private EntitySet<Registro_Avance_Academico> _Registro_Avance_Academico;
		
		private EntitySet<Registro_Asistencia> _Registro_Asistencia;
		
		private EntitySet<Registro_Asistencia> _Registro_Asistencia1;
		
		private EntityRef<Persona> _Persona;
		
		private EntityRef<Registro_Jardin> _Registro_Jardin;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRegistroNIUPChanging(long value);
    partial void OnRegistroNIUPChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnFechaNacChanging(System.DateTime value);
    partial void OnFechaNacChanged();
    partial void OnTipoSangreChanging(string value);
    partial void OnTipoSangreChanged();
    partial void OnCiudadNacimientoChanging(string value);
    partial void OnCiudadNacimientoChanged();
    partial void OnDocAcudienteChanging(long value);
    partial void OnDocAcudienteChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnEPSChanging(string value);
    partial void OnEPSChanged();
    partial void OnIdJardinChanging(System.Nullable<int> value);
    partial void OnIdJardinChanged();
    #endregion
		
		public RegistroNinios()
		{
			this._Registro_Avance_Academico = new EntitySet<Registro_Avance_Academico>(new Action<Registro_Avance_Academico>(this.attach_Registro_Avance_Academico), new Action<Registro_Avance_Academico>(this.detach_Registro_Avance_Academico));
			this._Registro_Asistencia = new EntitySet<Registro_Asistencia>(new Action<Registro_Asistencia>(this.attach_Registro_Asistencia), new Action<Registro_Asistencia>(this.detach_Registro_Asistencia));
			this._Registro_Asistencia1 = new EntitySet<Registro_Asistencia>(new Action<Registro_Asistencia>(this.attach_Registro_Asistencia1), new Action<Registro_Asistencia>(this.detach_Registro_Asistencia1));
			this._Persona = default(EntityRef<Persona>);
			this._Registro_Jardin = default(EntityRef<Registro_Jardin>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistroNIUP", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long RegistroNIUP
		{
			get
			{
				return this._RegistroNIUP;
			}
			set
			{
				if ((this._RegistroNIUP != value))
				{
					this.OnRegistroNIUPChanging(value);
					this.SendPropertyChanging();
					this._RegistroNIUP = value;
					this.SendPropertyChanged("RegistroNIUP");
					this.OnRegistroNIUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNac", DbType="DateTime NOT NULL")]
		public System.DateTime FechaNac
		{
			get
			{
				return this._FechaNac;
			}
			set
			{
				if ((this._FechaNac != value))
				{
					this.OnFechaNacChanging(value);
					this.SendPropertyChanging();
					this._FechaNac = value;
					this.SendPropertyChanged("FechaNac");
					this.OnFechaNacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoSangre", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TipoSangre
		{
			get
			{
				return this._TipoSangre;
			}
			set
			{
				if ((this._TipoSangre != value))
				{
					this.OnTipoSangreChanging(value);
					this.SendPropertyChanging();
					this._TipoSangre = value;
					this.SendPropertyChanged("TipoSangre");
					this.OnTipoSangreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CiudadNacimiento", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CiudadNacimiento
		{
			get
			{
				return this._CiudadNacimiento;
			}
			set
			{
				if ((this._CiudadNacimiento != value))
				{
					this.OnCiudadNacimientoChanging(value);
					this.SendPropertyChanging();
					this._CiudadNacimiento = value;
					this.SendPropertyChanged("CiudadNacimiento");
					this.OnCiudadNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocAcudiente", DbType="BigInt NOT NULL")]
		public long DocAcudiente
		{
			get
			{
				return this._DocAcudiente;
			}
			set
			{
				if ((this._DocAcudiente != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDocAcudienteChanging(value);
					this.SendPropertyChanging();
					this._DocAcudiente = value;
					this.SendPropertyChanged("DocAcudiente");
					this.OnDocAcudienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EPS
		{
			get
			{
				return this._EPS;
			}
			set
			{
				if ((this._EPS != value))
				{
					this.OnEPSChanging(value);
					this.SendPropertyChanging();
					this._EPS = value;
					this.SendPropertyChanged("EPS");
					this.OnEPSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdJardin", DbType="Int")]
		public System.Nullable<int> IdJardin
		{
			get
			{
				return this._IdJardin;
			}
			set
			{
				if ((this._IdJardin != value))
				{
					if (this._Registro_Jardin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdJardinChanging(value);
					this.SendPropertyChanging();
					this._IdJardin = value;
					this.SendPropertyChanged("IdJardin");
					this.OnIdJardinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RegistroNinios_Registro_Avance_Academico", Storage="_Registro_Avance_Academico", ThisKey="RegistroNIUP", OtherKey="idNinio")]
		public EntitySet<Registro_Avance_Academico> Registro_Avance_Academico
		{
			get
			{
				return this._Registro_Avance_Academico;
			}
			set
			{
				this._Registro_Avance_Academico.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RegistroNinios_Registro_Asistencia", Storage="_Registro_Asistencia", ThisKey="RegistroNIUP", OtherKey="IdNinio")]
		public EntitySet<Registro_Asistencia> Registro_Asistencia
		{
			get
			{
				return this._Registro_Asistencia;
			}
			set
			{
				this._Registro_Asistencia.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RegistroNinios_Registro_Asistencia1", Storage="_Registro_Asistencia1", ThisKey="RegistroNIUP", OtherKey="IdNinio")]
		public EntitySet<Registro_Asistencia> Registro_Asistencia1
		{
			get
			{
				return this._Registro_Asistencia1;
			}
			set
			{
				this._Registro_Asistencia1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_RegistroNinios", Storage="_Persona", ThisKey="DocAcudiente", OtherKey="Cedula", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.RegistroNinios.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.RegistroNinios.Add(this);
						this._DocAcudiente = value.Cedula;
					}
					else
					{
						this._DocAcudiente = default(long);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Registro_Jardin_RegistroNinios", Storage="_Registro_Jardin", ThisKey="IdJardin", OtherKey="IdJardin", IsForeignKey=true)]
		public Registro_Jardin Registro_Jardin
		{
			get
			{
				return this._Registro_Jardin.Entity;
			}
			set
			{
				Registro_Jardin previousValue = this._Registro_Jardin.Entity;
				if (((previousValue != value) 
							|| (this._Registro_Jardin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Registro_Jardin.Entity = null;
						previousValue.RegistroNinios.Remove(this);
					}
					this._Registro_Jardin.Entity = value;
					if ((value != null))
					{
						value.RegistroNinios.Add(this);
						this._IdJardin = value.IdJardin;
					}
					else
					{
						this._IdJardin = default(Nullable<int>);
					}
					this.SendPropertyChanged("Registro_Jardin");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Registro_Avance_Academico(Registro_Avance_Academico entity)
		{
			this.SendPropertyChanging();
			entity.RegistroNinios = this;
		}
		
		private void detach_Registro_Avance_Academico(Registro_Avance_Academico entity)
		{
			this.SendPropertyChanging();
			entity.RegistroNinios = null;
		}
		
		private void attach_Registro_Asistencia(Registro_Asistencia entity)
		{
			this.SendPropertyChanging();
			entity.RegistroNinios = this;
		}
		
		private void detach_Registro_Asistencia(Registro_Asistencia entity)
		{
			this.SendPropertyChanging();
			entity.RegistroNinios = null;
		}
		
		private void attach_Registro_Asistencia1(Registro_Asistencia entity)
		{
			this.SendPropertyChanging();
			entity.RegistroNinios1 = this;
		}
		
		private void detach_Registro_Asistencia1(Registro_Asistencia entity)
		{
			this.SendPropertyChanging();
			entity.RegistroNinios1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rol")]
	public partial class Rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRol;
		
		private string _nombreRol;
		
		private string _descripcion;
		
		private EntitySet<Persona> _Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRolChanging(int value);
    partial void OnidRolChanged();
    partial void OnnombreRolChanging(string value);
    partial void OnnombreRolChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public Rol()
		{
			this._Persona = new EntitySet<Persona>(new Action<Persona>(this.attach_Persona), new Action<Persona>(this.detach_Persona));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRol", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idRol
		{
			get
			{
				return this._idRol;
			}
			set
			{
				if ((this._idRol != value))
				{
					this.OnidRolChanging(value);
					this.SendPropertyChanging();
					this._idRol = value;
					this.SendPropertyChanged("idRol");
					this.OnidRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreRol", DbType="VarChar(50)")]
		public string nombreRol
		{
			get
			{
				return this._nombreRol;
			}
			set
			{
				if ((this._nombreRol != value))
				{
					this.OnnombreRolChanging(value);
					this.SendPropertyChanging();
					this._nombreRol = value;
					this.SendPropertyChanged("nombreRol");
					this.OnnombreRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Persona", Storage="_Persona", ThisKey="idRol", OtherKey="idRol")]
		public EntitySet<Persona> Persona
		{
			get
			{
				return this._Persona;
			}
			set
			{
				this._Persona.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Persona(Persona entity)
		{
			this.SendPropertyChanging();
			entity.Rol = this;
		}
		
		private void detach_Persona(Persona entity)
		{
			this.SendPropertyChanging();
			entity.Rol = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Anuncios")]
	public partial class Anuncios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAnuncio;
		
		private string _Descripcion;
		
		private System.DateTime _fechaAnuncio;
		
		private string _estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAnuncioChanging(int value);
    partial void OnIdAnuncioChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnfechaAnuncioChanging(System.DateTime value);
    partial void OnfechaAnuncioChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public Anuncios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAnuncio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAnuncio
		{
			get
			{
				return this._IdAnuncio;
			}
			set
			{
				if ((this._IdAnuncio != value))
				{
					this.OnIdAnuncioChanging(value);
					this.SendPropertyChanging();
					this._IdAnuncio = value;
					this.SendPropertyChanged("IdAnuncio");
					this.OnIdAnuncioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaAnuncio", DbType="Date NOT NULL")]
		public System.DateTime fechaAnuncio
		{
			get
			{
				return this._fechaAnuncio;
			}
			set
			{
				if ((this._fechaAnuncio != value))
				{
					this.OnfechaAnuncioChanging(value);
					this.SendPropertyChanging();
					this._fechaAnuncio = value;
					this.SendPropertyChanged("fechaAnuncio");
					this.OnfechaAnuncioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Registro_Asistencia")]
	public partial class Registro_Asistencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _idRegistro;
		
		private long _IdNinio;
		
		private System.DateTime _fecha;
		
		private string _DesEstadoNinio;
		
		private EntityRef<RegistroNinios> _RegistroNinios;
		
		private EntityRef<RegistroNinios> _RegistroNinios1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRegistroChanging(long value);
    partial void OnidRegistroChanged();
    partial void OnIdNinioChanging(long value);
    partial void OnIdNinioChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void OnDesEstadoNinioChanging(string value);
    partial void OnDesEstadoNinioChanged();
    #endregion
		
		public Registro_Asistencia()
		{
			this._RegistroNinios = default(EntityRef<RegistroNinios>);
			this._RegistroNinios1 = default(EntityRef<RegistroNinios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRegistro", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long idRegistro
		{
			get
			{
				return this._idRegistro;
			}
			set
			{
				if ((this._idRegistro != value))
				{
					this.OnidRegistroChanging(value);
					this.SendPropertyChanging();
					this._idRegistro = value;
					this.SendPropertyChanged("idRegistro");
					this.OnidRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNinio", DbType="BigInt NOT NULL")]
		public long IdNinio
		{
			get
			{
				return this._IdNinio;
			}
			set
			{
				if ((this._IdNinio != value))
				{
					if ((this._RegistroNinios.HasLoadedOrAssignedValue || this._RegistroNinios1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdNinioChanging(value);
					this.SendPropertyChanging();
					this._IdNinio = value;
					this.SendPropertyChanged("IdNinio");
					this.OnIdNinioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DesEstadoNinio", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DesEstadoNinio
		{
			get
			{
				return this._DesEstadoNinio;
			}
			set
			{
				if ((this._DesEstadoNinio != value))
				{
					this.OnDesEstadoNinioChanging(value);
					this.SendPropertyChanging();
					this._DesEstadoNinio = value;
					this.SendPropertyChanged("DesEstadoNinio");
					this.OnDesEstadoNinioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RegistroNinios_Registro_Asistencia", Storage="_RegistroNinios", ThisKey="IdNinio", OtherKey="RegistroNIUP", IsForeignKey=true)]
		public RegistroNinios RegistroNinios
		{
			get
			{
				return this._RegistroNinios.Entity;
			}
			set
			{
				RegistroNinios previousValue = this._RegistroNinios.Entity;
				if (((previousValue != value) 
							|| (this._RegistroNinios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RegistroNinios.Entity = null;
						previousValue.Registro_Asistencia.Remove(this);
					}
					this._RegistroNinios.Entity = value;
					if ((value != null))
					{
						value.Registro_Asistencia.Add(this);
						this._IdNinio = value.RegistroNIUP;
					}
					else
					{
						this._IdNinio = default(long);
					}
					this.SendPropertyChanged("RegistroNinios");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RegistroNinios_Registro_Asistencia1", Storage="_RegistroNinios1", ThisKey="IdNinio", OtherKey="RegistroNIUP", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public RegistroNinios RegistroNinios1
		{
			get
			{
				return this._RegistroNinios1.Entity;
			}
			set
			{
				RegistroNinios previousValue = this._RegistroNinios1.Entity;
				if (((previousValue != value) 
							|| (this._RegistroNinios1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RegistroNinios1.Entity = null;
						previousValue.Registro_Asistencia1.Remove(this);
					}
					this._RegistroNinios1.Entity = value;
					if ((value != null))
					{
						value.Registro_Asistencia1.Add(this);
						this._IdNinio = value.RegistroNIUP;
					}
					else
					{
						this._IdNinio = default(long);
					}
					this.SendPropertyChanged("RegistroNinios1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SP_LOGINResult
	{
		
		private string _Nombres;
		
		private int _idRol;
		
		private string _Correo;
		
		public SP_LOGINResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRol", DbType="Int NOT NULL")]
		public int idRol
		{
			get
			{
				return this._idRol;
			}
			set
			{
				if ((this._idRol != value))
				{
					this._idRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
	}
	
	public partial class SP_LOGIN_WEBResult
	{
		
		private long _Cedula;
		
		private string _Nombres;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Telefono;
		
		private string _Celular;
		
		private string _Direccion;
		
		private string _Correo;
		
		private string _Clave;
		
		private int _idRol;
		
		public SP_LOGIN_WEBResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="BigInt NOT NULL")]
		public long Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this._Celular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this._Clave = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRol", DbType="Int NOT NULL")]
		public int idRol
		{
			get
			{
				return this._idRol;
			}
			set
			{
				if ((this._idRol != value))
				{
					this._idRol = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
